#!/bin/sh -x

set -e

version=1.7

# github repository to pull from
repname=samtools

# directory to do the pull and build
TMPDIR=~/tmp/release/$version
TMPDIR=`readlink -m $TMPDIR`

# clean up TMPDIR
mkdir -p $TMPDIR
cd $TMPDIR

# build each repository in turn
for repo in htslib samtools bcftools; do
    echo Building $repo
    rm -fr $repo
    git clone http://github.com/$repname/$repo.git

    cd $repo

    git checkout --track origin/master
    git merge --no-ff --no-commit develop

    date=`date +"%d %B %Y"`
    if [ -e version.sh ] ; then
	sed -i "s/^VERSION=[1-9].*/VERSION=$version/" version.sh
	git add version.sh
    else
	sed -i "s/PACKAGE_VERSION[ ][ ]*=[ ][ ]*[1-9].*/PACKAGE_VERSION = $version/" Makefile
	git add Makefile
    fi
    if [ -e htsfile.1 ]; then
        sed -i "s/^.TH.*/.TH htsfile 1 \"$date\" \"htslib-$version\" \"Bioinformatics tools\"/" htsfile.1
        git add htsfile.1
    fi
    if [ -e tabix.1 ]; then
        sed -i "s/^.TH.*/.TH tabix 1 \"$date\" \"htslib-$version\" \"Bioinformatics tools\"/" tabix.1
        git add tabix.1
    fi
    if [ -e samtools.1 ]; then
        sed -i "s/^.TH.*/.TH samtools 1 \"$date\" \"samtools-$version\" \"Bioinformatics tools\"/" samtools.1
        git add samtools.1
    fi
    if [ -e misc/wgsim.1 ]; then
        sed -i "s/^.TH.*/.TH wgsim 1 \"$date\" \"samtools-$version\" \"Bioinformatics tools\"/" misc/wgsim.1
        git add misc/wgsim.1
    fi
    if [ -e README ]; then
        sed -i "s/samtools-.*/samtools-$version # Within the unpacked release directory/" README
        sed -i "s/htslib-.*/htslib-$version/" README
        git add README
    fi
    if [ -e bam.h ]; then
        sed -i "s/BAM_VERSION.*/BAM_VERSION \"$version\"/" bam.h
        git add bam.h
    fi

    if [ -e doc/bcftools.1 ]; then
        echo make DOC_VERSION=\"$version\" DOC_DATE=`date +"%Y-%m-%d"` docs
        make DOC_VERSION=\"$version\" DOC_DATE=`date +"%Y-%m-%d"` docs
        git add doc/bcftools.1 doc/bcftools.html
    fi
    # git commit --no-verify -m "Release $version: summary"
    cd ..
done
