#!/bin/sh

dir=$1
tag=$2
tarsuffix=$3
projver=${dir##*/}-$tag

rm -rf $projver
(cd $dir && git archive --prefix=$projver/ $tag) | tar x
(cd $projver && find * -type f -print) |
  while IFS= read -r file
  do
    touch -t $(cd $dir && git rev-list --format=format:%ai -n1 $tag -- $file |
      sed '/^commit/d;s/ [-+].*$//;s/[- :]//g;s/\(..\)$/.\1/') $projver/$file
  done
if test -f $projver/configure.ac
then
  (cd $projver
  touch config.mk
  unset MAKEFLAGS MAKELEVEL MAKEOVERRIDES MFLAGS
  grep -q AX_ configure.ac && (grep -q m4_include configure.ac || aclocal)
  test -e config.h.in || autoheader
  autoconf --warnings=all
  rm -rf autom4te.cache config.mk)
  # Look for unexpanded autoconf macros
  egrep '^[^#]*\<A[A-Z]_[A-Z_]*' $projver/configure && exit 1
fi
rm -f $projver$tarsuffix.tar.bz2
tar cjf $projver$tarsuffix.tar.bz2 $projver
rm -r $projver
