FROM archlinux:base-devel AS buildimg

RUN pacman -Syyu --noconfirm && \
    pacman -Sy --noconfirm base-devel git libdeflate

FROM buildimg AS test

RUN git clone --branch=master --recurse-submodules https://github.com/samtools/htslib.git && \
    git	clone --branch=master https://github.com/samtools/samtools.git && \
    git clone --branch=master https://github.com/samtools/bcftools.git && \
    ( cd htslib && autoreconf -i && ./configure && make -j 4 && make check ) && \
    ( cd samtools && autoreconf -i && ./configure && make -j 4 && make check ) && \
    ( cd bcftools && autoreconf -i && ./configure && make -j 4 && make check )
