FROM alpine:3.23 AS buildimg

RUN apk update && \
    apk add git autoconf automake make gcc musl-dev perl bash zlib-dev bzip2-dev xz-dev libdeflate-dev curl-dev openssl-dev ncurses-dev


FROM buildimg AS test

RUN git clone --branch=master --recurse-submodules https://github.com/samtools/htslib.git && \
    git	clone --branch=master https://github.com/samtools/samtools.git && \
    git clone --branch=master https://github.com/samtools/bcftools.git && \
    ( cd htslib && autoreconf -i && ./configure && make -j 4 && make check ) && \
    ( cd samtools && autoreconf -i && ./configure && make -j 4 && make check ) && \
    ( cd bcftools && autoreconf -i && ./configure && make -j 4 && make check )
